### ISSUE TITLE
Impossible to enable public key pinning for Android API below 24 in default networking library

### ISSUE THREAD

**Issue by tluksa** [gini/gini-vision-lib-android#220]
Maybe I missed something but I didn't find the way to enable public key pinning while using default networking library. It would be helpful to have setter inside GiniVisionDefaultNetworkService.Builder for that.

**Comment by a-szotyori** [comment]
Hi, thank you for the issue! We are looking into it and will get back to you soon with a solution.

**Comment by a-szotyori** [comment]
Setter `setNetworkSecurityConfigResId()` added to `GiniVisionDefaultNetworkService.Builder` in version `3.0.1`.
