### ISSUE TITLE
Create possibility to force language for application

### ISSUE THREAD

**Issue by tluksa** [gini/gini-vision-lib-android#232]
Hi,
In short. We have multiple clients. Majority of them uses default android implementation for locale(language) resolution but some of them require to hardcode the language. So it means that if we force language to "de", selecting different language in android settings like "en", "fr", "it" or etc. doesn't affect the app and we still see "de" translations.
We are forcing this behaviour by overriding "attachBaseContext" in Activity and Application. And we apply forced language to Configuration.

The problem is that these changes doesn't affect gini vision library because we don't control activities and application of it.

Would it be possible to implement forced language behaviour in gini vision library?

**Comment by a-szotyori** [comment]
Hi, thank you for contacting us. I forwarded your request to my colleagues.

I would like to ask you to send an email to technical-support@gini.net referencing this issue together with details about your company. For confidentiality reasons we will continue discussing your request there.

Have a great day!

**Comment by tluksa** [comment]
Thank you for the answer. We decided to take different path for now.
If we will have this issue at the future we will contact tech-support.
