### ISSUE TITLE
Parallel Builds on CI

### ISSUE THREAD

**Issue by EarlOfEgo** [gini/gini-vision-lib-android#75]
Right now the builds take ages on our CI, we should make as much as possible of the stages parallel.
Pipeline does support parallelism but not nicely so far imo. We should wait till `Declarative - 1.2` is released and then implement it. See [this issue](https://issues.jenkins-ci.org/browse/JENKINS-41334) for more information.

**Comment by a-szotyori** [comment]
Tried running the unit test and the instrumentation tests on emulators in parallel, but unfortunately it was very unstable. Each parallel stage was executing gradle in its own folder and thus gradle tasks should not interfere with each other, but for some reasons they did. The causes can be related to how Jenkins runs stage in parallel combined with how gradle caches work, etc. Debugging this would take a significant effort and it's just not worth doing it to shave off only ~5 minutes from the build time.

Parallel stages were enabled in this [commit](https://github.com/gini/gini-vision-lib-android/commit/7a7f138a25028859769181b2f292c5085117b1fc) and then reverted to serial execution in this [commit](https://github.com/gini/gini-vision-lib-android/commit/7baf15373c4a458cf628d1979173344acdef743d).
